FROM python:3.11-slim

WORKDIR /app
ENV PYTHONPATH=/app

RUN apt-get update && apt-get install -y build-essential

COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

COPY backend /app/backend
COPY workers /app/workers

CMD ["celery", "-A", "workers.celery_app", "worker", "--loglevel=info", "--pool=solo", "-Q", "review_queue"]
